apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13.3
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: $DB_USERNAME
            - name: POSTGRES_PASSWORD
              value: $DB_PASSWORD
            - name: POSTGRES_DB
              value: $DB_PASSWORD
